# Code generated by butter. DO NOT EDIT.
# Source: queries/extract_profile.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- extract_profile (:one) ----


class ExtractProfileRow(pydantic.BaseModel):
    """One result row of `extract_profile`."""

    settings_json: typing.Any | None
    timezone: str | None
    theme_json: typing.Any | None
    theme_text: str | None


class ExtractProfileParams(pydantic.BaseModel):
    """Parameters of `extract_profile`."""

    email: str


EXTRACT_PROFILE = """
SELECT
    profile -> 'settings' AS settings_json,
    profile ->> 'timezone' AS timezone,
    profile #> '{settings,theme}' AS theme_json,
    profile #>> '{settings,theme}' AS theme_text
FROM public.accounts
WHERE email = $1
"""


async def extract_profile(
    cursor: aiosqlite.Cursor,
    *,
    email: str,
) -> ExtractProfileRow | None:
    """Runs `extract_profile`."""
    params = tuple(ExtractProfileParams(email=email).model_dump(by_alias=True).values())
    await cursor.execute(EXTRACT_PROFILE, params)
    row = await cursor.fetchone()
    return ExtractProfileRow.model_validate(_row_dict(ExtractProfileRow, row)) if row is not None else None
