# Code generated by butter. DO NOT EDIT.
# Source: queries/find_account.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- find_account (:one) ----


class FindAccountRow(pydantic.BaseModel):
    """One result row of `find_account`."""

    id: int
    external_id: str
    email: str
    profile: typing.Any | None
    tags: list[str | None] | None
    score_matrix: list[list[int | None]]


class FindAccountParams(pydantic.BaseModel):
    """Parameters of `find_account`."""

    email: str
    id: int
    tags: list[str | None]


FIND_ACCOUNT = """
SELECT id, external_id, email, profile, tags, score_matrix
FROM public.accounts
WHERE id > $2 AND (email = $1 OR lower(email) = lower($1)) AND tags = $3
"""


async def find_account(
    cursor: aiosqlite.Cursor,
    *,
    email: str,
    id: int,
    tags: list[str | None],
) -> FindAccountRow | None:
    """Runs `find_account`."""
    params = tuple(FindAccountParams(email=email, id=id, tags=tags).model_dump(by_alias=True).values())
    await cursor.execute(FIND_ACCOUNT, params)
    row = await cursor.fetchone()
    return FindAccountRow.model_validate(_row_dict(FindAccountRow, row)) if row is not None else None
