# Code generated by butter. DO NOT EDIT.
# Source: queries/list_account_activity.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- list_account_activity (:many) ----


class ListAccountActivityRow(pydantic.BaseModel):
    """One result row of `list_account_activity`."""

    id: int
    display_name: str
    amount: float | None
    memo: str | None


class ListAccountActivityParams(pydantic.BaseModel):
    """Parameters of `list_account_activity`."""

    minimum: float


LIST_ACCOUNT_ACTIVITY = """
WITH recent AS (
    SELECT account_id, amount, memo
    FROM invoice
    WHERE amount >= :minimum
)
SELECT a.id, a.display_name, r.amount, r.memo
FROM account AS a
LEFT JOIN recent AS r ON r.account_id = a.id
UNION ALL
SELECT a.id, a.display_name, NULL AS amount, 'no invoice' AS memo
FROM account AS a
WHERE NOT EXISTS (SELECT 1 FROM invoice AS i WHERE i.account_id = a.id)
ORDER BY id
"""


async def list_account_activity(
    cursor: aiosqlite.Cursor,
    *,
    minimum: float,
) -> list[ListAccountActivityRow]:
    """Runs `list_account_activity`."""
    params = ListAccountActivityParams(minimum=minimum).model_dump(by_alias=True)
    await cursor.execute(LIST_ACCOUNT_ACTIVITY, params)
    return [ListAccountActivityRow.model_validate(_row_dict(ListAccountActivityRow, row)) for row in await cursor.fetchall()]
