use crate::query::{QueryCardinality, QueryInputField, QueryOutputField, QueryParseResult};
use std::fs;
use std::path::Path;

const PYTHON_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

fn is_python_keyword(name: &str) -> bool {
    PYTHON_KEYWORDS.contains(&name)
}

/// Convert a `snake_case` or `PascalCase` name to `PascalCase`.
fn to_pascal_case(name: &str) -> String {
    if name.contains('_') {
        name.split('_')
            .filter(|s| !s.is_empty())
            .map(|s| {
                let mut c = s.chars();
                match c.next() {
                    None => String::new(),
                    Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                }
            })
            .collect()
    } else {
        let mut c = name.chars();
        match c.next() {
            None => String::new(),
            Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
        }
    }
}

/// Convert a name to `SCREAMING_SNAKE_CASE`.
fn to_screaming_snake(name: &str) -> String {
    if name.contains('_') {
        name.to_uppercase()
    } else {
        let mut result = String::new();
        for (i, c) in name.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_uppercase().next().unwrap());
        }
        result
    }
}

/// Sanitise a field name: append `_` if it is a Python keyword.
fn sanitise_field_name(name: &str) -> String {
    if is_python_keyword(name) {
        format!("{}_", name)
    } else {
        name.to_string()
    }
}

/// Collect non-typing stdlib imports needed for the given type strings.
fn collect_stdlib_imports(types: &[&str]) -> Vec<&'static str> {
    let mut imports: Vec<&'static str> = Vec::new();
    if types.iter().any(|t| t.starts_with("datetime.")) {
        imports.push("import datetime");
    }
    if types.iter().any(|t| *t == "Decimal") {
        imports.push("from decimal import Decimal");
    }
    imports
}

/// Generate a `.py` file from a list of parsed queries and write it to `output_path`.
pub fn generate_python_file(
    queries: &[QueryParseResult],
    source_filename: &str,
    output_path: &Path,
) -> Result<(), std::io::Error> {
    // Detect naming collisions
    let mut class_names_seen: Vec<String> = Vec::new();
    for query in queries {
        if matches!(query.annotation.cardinality, QueryCardinality::Exec) {
            continue;
        }
        let class_name = format!("{}Row", to_pascal_case(&query.annotation.name));
        if class_names_seen.contains(&class_name) {
            eprintln!(
                "Error: duplicate row class name \"{}\" in \"{}\", skipping file generation",
                class_name, source_filename
            );
            return Ok(());
        }
        class_names_seen.push(class_name);
    }

    // Gather all type strings to determine imports
    let mut all_types: Vec<String> = Vec::new();
    let has_one = queries
        .iter()
        .any(|q| matches!(q.annotation.cardinality, QueryCardinality::One));

    for query in queries {
        for f in &query.input_fields {
            all_types.push(f.data_type.clone());
        }
        // Output field types are currently all Any (no data_type on QueryOutputField yet)
    }
    if has_one {
        all_types.push("Optional".to_string());
    }

    let type_refs: Vec<&str> = all_types.iter().map(|s| s.as_str()).collect();
    let stdlib_imports = collect_stdlib_imports(&type_refs);

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "# GENERATED BY icantbelieveitsnotsql -- DO NOT EDIT\n# Source: {}\n\n",
        source_filename
    ));

    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import dataclasses\n");
    for import in &stdlib_imports {
        out.push_str(import);
        out.push('\n');
    }

    // Single consolidated typing import
    {
        let mut typing_names: Vec<&str> = vec!["Any"];
        if has_one {
            typing_names.push("Optional");
        }
        typing_names.push("Protocol");
        out.push_str(&format!("from typing import {}\n", typing_names.join(", ")));
    }
    out.push('\n');

    // _Cursor protocol
    out.push_str("\nclass _Cursor(Protocol):\n");
    out.push_str("    def execute(self, sql: str, parameters: Any = ...) -> Any: ...\n");
    out.push_str("    def fetchone(self) -> tuple[Any, ...] | None: ...\n");
    out.push_str("    def fetchall(self) -> list[tuple[Any, ...]]: ...\n");

    // One block per query
    for query in queries {
        let fn_name = query.annotation.name.to_lowercase();
        let pascal_name = to_pascal_case(&query.annotation.name);
        let const_name = format!("_{}_SQL", to_screaming_snake(&query.annotation.name));
        let row_class = format!("{}Row", pascal_name);

        out.push_str("\n\n");
        out.push_str(&format!("# {}\n", "-".repeat(75 - fn_name.len().min(73))));
        out.push_str(&format!("# {}\n", fn_name));
        out.push_str(&format!("# {}\n", "-".repeat(75 - fn_name.len().min(73))));

        // SQL constant — strip trailing semicolon
        let sql_text = query
            .statement
            .to_string()
            .trim_end_matches(';')
            .trim()
            .to_string();
        out.push_str(&format!(
            "\n{} = \"\"\"\n{}\n\"\"\"\n",
            const_name, sql_text
        ));

        let is_exec = matches!(query.annotation.cardinality, QueryCardinality::Exec);

        // Row dataclass (only for :one and :many)
        if !is_exec {
            out.push('\n');
            out.push('\n');
            out.push_str("@dataclasses.dataclass\n");
            out.push_str(&format!("class {}:\n", row_class));
            if query.output_fields.is_empty() {
                out.push_str("    pass\n");
            } else {
                for field in &query.output_fields {
                    let field_name = sanitise_field_name(&field.name);
                    let py_type = output_field_python_type(field);
                    out.push_str(&format!("    {}: {}\n", field_name, py_type));
                }
            }
        }

        let return_type = match &query.annotation.cardinality {
            QueryCardinality::One => format!("Optional[{}]", row_class),
            QueryCardinality::Many => format!("list[{}]", row_class),
            QueryCardinality::Exec => "None".to_string(),
        };

        let mut params = vec!["cursor: _Cursor".to_string()];
        if !query.input_fields.is_empty() {
            params.push("*".to_string());
            for f in &query.input_fields {
                let param_name = sanitise_field_name(&f.name);
                params.push(format!("{}: {}", param_name, f.data_type));
            }
        }

        out.push('\n');
        out.push_str(&format!(
            "def {}({}) -> {}:\n",
            fn_name,
            params.join(", "),
            return_type
        ));

        let execute_args = build_execute_args(&query.input_fields);
        if execute_args.is_empty() {
            out.push_str(&format!("    cursor.execute({})\n", const_name));
        } else {
            out.push_str(&format!(
                "    cursor.execute({}, {})\n",
                const_name, execute_args
            ));
        }

        match &query.annotation.cardinality {
            QueryCardinality::Exec => {}
            QueryCardinality::One => {
                out.push_str("    row = cursor.fetchone()\n");
                out.push_str("    if row is None:\n");
                out.push_str("        return None\n");
                out.push_str(&format!("    return {}(\n", row_class));
                for (i, field) in query.output_fields.iter().enumerate() {
                    let field_name = sanitise_field_name(&field.name);
                    out.push_str(&format!("        {}=row[{}],\n", field_name, i));
                }
                out.push_str("    )\n");
            }
            QueryCardinality::Many => {
                out.push_str("    rows = cursor.fetchall()\n");
                out.push_str(&format!("    return [\n        {}(\n", row_class));
                for (i, field) in query.output_fields.iter().enumerate() {
                    let field_name = sanitise_field_name(&field.name);
                    out.push_str(&format!("            {}=row[{}],\n", field_name, i));
                }
                out.push_str("        )\n        for row in rows\n    ]\n");
            }
        }
    }

    out.push('\n');

    fs::write(output_path, out)
}

/// Build the second argument to `cursor.execute()`.
fn build_execute_args(input_fields: &[QueryInputField]) -> String {
    if input_fields.is_empty() {
        return String::new();
    }

    let all_named = input_fields.iter().all(|f| !f.name.starts_with('$'));

    if all_named {
        let pairs: Vec<String> = input_fields
            .iter()
            .map(|f| {
                let safe = sanitise_field_name(&f.name);
                format!("\"{}\": {}", f.name, safe)
            })
            .collect();
        format!("{{{}}}", pairs.join(", "))
    } else {
        let args: Vec<String> = input_fields
            .iter()
            .map(|f| sanitise_field_name(&f.name))
            .collect();
        if args.len() == 1 {
            format!("({},)", args[0])
        } else {
            format!("({})", args.join(", "))
        }
    }
}

/// Get the Python type annotation for an output field.
/// Currently falls back to Any — output fields don't carry data_type yet.
fn output_field_python_type(_field: &QueryOutputField) -> &'static str {
    "Any"
}
