# Code generated by butter. DO NOT EDIT.
# Source: sql/butter/cache_entry.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- create_table_cache_entry (:exec) ----

CREATE_TABLE_CACHE_ENTRY = """
CREATE TABLE IF NOT EXISTS cache_entry (
    key TEXT NOT NULL PRIMARY KEY UNIQUE,
    value BLOB NOT NULL
)
"""


async def create_table_cache_entry(
    cursor: aiosqlite.Cursor,
) -> None:
    """Runs `create_table_cache_entry`."""
    await cursor.execute(CREATE_TABLE_CACHE_ENTRY)


# ---- select_many_cache_entry (:many) ----


class SelectManyCacheEntryRow(pydantic.BaseModel):
    """One result row of `select_many_cache_entry`."""

    key: str
    value: bytes


SELECT_MANY_CACHE_ENTRY = """
SELECT *
FROM cache_entry
"""


async def select_many_cache_entry(
    cursor: aiosqlite.Cursor,
) -> list[SelectManyCacheEntryRow]:
    """Runs `select_many_cache_entry`."""
    await cursor.execute(SELECT_MANY_CACHE_ENTRY)
    return [SelectManyCacheEntryRow.model_validate(_row_dict(SelectManyCacheEntryRow, row)) for row in await cursor.fetchall()]


# ---- select_many_cache_entry_by_key (:many) ----


class SelectManyCacheEntryByKeyRow(pydantic.BaseModel):
    """One result row of `select_many_cache_entry_by_key`."""

    key: str
    value: bytes


class SelectManyCacheEntryByKeyParams(pydantic.BaseModel):
    """Parameters of `select_many_cache_entry_by_key`."""

    key: str


SELECT_MANY_CACHE_ENTRY_BY_KEY = """
SELECT *
FROM cache_entry
WHERE key = :key
"""


async def select_many_cache_entry_by_key(
    cursor: aiosqlite.Cursor,
    *,
    key: str,
) -> list[SelectManyCacheEntryByKeyRow]:
    """Runs `select_many_cache_entry_by_key`."""
    params = SelectManyCacheEntryByKeyParams(key=key).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_CACHE_ENTRY_BY_KEY, params)
    return [SelectManyCacheEntryByKeyRow.model_validate(_row_dict(SelectManyCacheEntryByKeyRow, row)) for row in await cursor.fetchall()]


# ---- select_one_cache_entry_by_key (:one) ----


class SelectOneCacheEntryByKeyRow(pydantic.BaseModel):
    """One result row of `select_one_cache_entry_by_key`."""

    key: str
    value: bytes


class SelectOneCacheEntryByKeyParams(pydantic.BaseModel):
    """Parameters of `select_one_cache_entry_by_key`."""

    key: str


SELECT_ONE_CACHE_ENTRY_BY_KEY = """
SELECT *
FROM cache_entry
WHERE key = ?
"""


async def select_one_cache_entry_by_key(
    cursor: aiosqlite.Cursor,
    *,
    key: str,
) -> SelectOneCacheEntryByKeyRow | None:
    """A `?` placeholder is named after the column it is compared with."""
    params = tuple(SelectOneCacheEntryByKeyParams(key=key).model_dump(by_alias=True).values())
    await cursor.execute(SELECT_ONE_CACHE_ENTRY_BY_KEY, params)
    row = await cursor.fetchone()
    return SelectOneCacheEntryByKeyRow.model_validate(_row_dict(SelectOneCacheEntryByKeyRow, row)) if row is not None else None


# ---- insert_many_cache_entry (:execmany) ----


class InsertManyCacheEntryParams(pydantic.BaseModel):
    """Parameters of `insert_many_cache_entry`."""

    key: str
    value: bytes


INSERT_MANY_CACHE_ENTRY = """
INSERT INTO cache_entry (key, value)
VALUES (:key, :value)
"""


async def insert_many_cache_entry(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyCacheEntryParams],
) -> int:
    """Runs `insert_many_cache_entry`."""
    await cursor.executemany(INSERT_MANY_CACHE_ENTRY, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- count_cache_entry (:one) ----


class CountCacheEntryRow(pydantic.BaseModel):
    """One result row of `count_cache_entry`."""

    total: int


COUNT_CACHE_ENTRY = """
SELECT COUNT(*) AS total
FROM cache_entry
"""


async def count_cache_entry(
    cursor: aiosqlite.Cursor,
) -> CountCacheEntryRow | None:
    """Runs `count_cache_entry`."""
    await cursor.execute(COUNT_CACHE_ENTRY)
    row = await cursor.fetchone()
    return CountCacheEntryRow.model_validate(_row_dict(CountCacheEntryRow, row)) if row is not None else None
