# Code generated by butter. DO NOT EDIT.
# Source: sql/butter/membership.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- create_table_membership (:exec) ----

CREATE_TABLE_MEMBERSHIP_1 = """
CREATE TABLE IF NOT EXISTS membership (
    user_id TEXT NOT NULL,
    group_id TEXT NOT NULL
)
"""

CREATE_TABLE_MEMBERSHIP_2 = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_membership_user_id_group_id ON membership (user_id, group_id)
"""


async def create_table_membership(
    cursor: aiosqlite.Cursor,
) -> None:
    """Runs `create_table_membership`."""
    await cursor.execute(CREATE_TABLE_MEMBERSHIP_1)
    await cursor.execute(CREATE_TABLE_MEMBERSHIP_2)


# ---- insert_many_membership (:execmany) ----


class InsertManyMembershipParams(pydantic.BaseModel):
    """Parameters of `insert_many_membership`."""

    user_id: str
    group_id: str


INSERT_MANY_MEMBERSHIP = """
INSERT INTO membership (user_id, group_id)
VALUES (:user_id, :group_id)
"""


async def insert_many_membership(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyMembershipParams],
) -> int:
    """Runs `insert_many_membership`."""
    await cursor.executemany(INSERT_MANY_MEMBERSHIP, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- insert_many_membership_ignore_conflicts (:execmany) ----


class InsertManyMembershipIgnoreConflictsParams(pydantic.BaseModel):
    """Parameters of `insert_many_membership_ignore_conflicts`."""

    user_id: str
    group_id: str


INSERT_MANY_MEMBERSHIP_IGNORE_CONFLICTS = """
INSERT INTO membership (user_id, group_id)
VALUES (:user_id, :group_id)
ON CONFLICT(user_id, group_id) DO NOTHING
"""


async def insert_many_membership_ignore_conflicts(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyMembershipIgnoreConflictsParams],
) -> int:
    """Runs `insert_many_membership_ignore_conflicts`."""
    await cursor.executemany(INSERT_MANY_MEMBERSHIP_IGNORE_CONFLICTS, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- select_many_membership_by_user_id (:many) ----


class SelectManyMembershipByUserIdRow(pydantic.BaseModel):
    """One result row of `select_many_membership_by_user_id`."""

    user_id: str
    group_id: str


class SelectManyMembershipByUserIdParams(pydantic.BaseModel):
    """Parameters of `select_many_membership_by_user_id`."""

    user_id: str


SELECT_MANY_MEMBERSHIP_BY_USER_ID = """
SELECT *
FROM membership
WHERE user_id = :user_id
"""


async def select_many_membership_by_user_id(
    cursor: aiosqlite.Cursor,
    *,
    user_id: str,
) -> list[SelectManyMembershipByUserIdRow]:
    """Runs `select_many_membership_by_user_id`."""
    params = SelectManyMembershipByUserIdParams(user_id=user_id).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_MEMBERSHIP_BY_USER_ID, params)
    return [SelectManyMembershipByUserIdRow.model_validate(_row_dict(SelectManyMembershipByUserIdRow, row)) for row in await cursor.fetchall()]


# ---- select_many_membership_with_cache_entry (:many) ----


class SelectManyMembershipWithCacheEntryRow(pydantic.BaseModel):
    """One result row of `select_many_membership_with_cache_entry`."""

    user_id: str
    group_id: str
    cached_value: bytes | None


class SelectManyMembershipWithCacheEntryParams(pydantic.BaseModel):
    """Parameters of `select_many_membership_with_cache_entry`."""

    user_id: str


SELECT_MANY_MEMBERSHIP_WITH_CACHE_ENTRY = """
SELECT m.user_id, m.group_id, c.value AS cached_value
FROM membership m
LEFT JOIN cache_entry c ON c.key = m.group_id
WHERE m.user_id = :user_id
"""


async def select_many_membership_with_cache_entry(
    cursor: aiosqlite.Cursor,
    *,
    user_id: str,
) -> list[SelectManyMembershipWithCacheEntryRow]:
    """A LEFT JOIN makes the joined columns nullable."""
    params = SelectManyMembershipWithCacheEntryParams(user_id=user_id).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_MEMBERSHIP_WITH_CACHE_ENTRY, params)
    return [SelectManyMembershipWithCacheEntryRow.model_validate(_row_dict(SelectManyMembershipWithCacheEntryRow, row)) for row in await cursor.fetchall()]
