# Code generated by butter. DO NOT EDIT.
# Source: sql/butter/tag.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- create_table_tag (:exec) ----

CREATE_TABLE_TAG_1 = """
CREATE TABLE IF NOT EXISTS tag (
    item_id TEXT NOT NULL,
    name TEXT NOT NULL
)
"""

CREATE_TABLE_TAG_2 = """
CREATE UNIQUE INDEX IF NOT EXISTS idx_tag_item_id_name ON tag (item_id, name)
"""


async def create_table_tag(
    cursor: aiosqlite.Cursor,
) -> None:
    """Runs `create_table_tag`."""
    await cursor.execute(CREATE_TABLE_TAG_1)
    await cursor.execute(CREATE_TABLE_TAG_2)


# ---- insert_many_tag (:execmany) ----


class InsertManyTagParams(pydantic.BaseModel):
    """Parameters of `insert_many_tag`."""

    item_id: str
    name: str


INSERT_MANY_TAG = """
INSERT INTO tag (item_id, name)
VALUES (:item_id, :name)
ON CONFLICT(item_id, name) DO NOTHING
"""


async def insert_many_tag(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyTagParams],
) -> int:
    """Runs `insert_many_tag`."""
    await cursor.executemany(INSERT_MANY_TAG, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- select_many_tag_name_by_item_id (:many) ----


class SelectManyTagNameByItemIdRow(pydantic.BaseModel):
    """One result row of `select_many_tag_name_by_item_id`."""

    name: str


class SelectManyTagNameByItemIdParams(pydantic.BaseModel):
    """Parameters of `select_many_tag_name_by_item_id`."""

    item_id: str


SELECT_MANY_TAG_NAME_BY_ITEM_ID = """
SELECT name
FROM tag
WHERE item_id = :item_id
ORDER BY name
"""


async def select_many_tag_name_by_item_id(
    cursor: aiosqlite.Cursor,
    *,
    item_id: str,
) -> list[SelectManyTagNameByItemIdRow]:
    """Runs `select_many_tag_name_by_item_id`."""
    params = SelectManyTagNameByItemIdParams(item_id=item_id).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_TAG_NAME_BY_ITEM_ID, params)
    return [SelectManyTagNameByItemIdRow.model_validate(_row_dict(SelectManyTagNameByItemIdRow, row)) for row in await cursor.fetchall()]
