# Code generated by butter. DO NOT EDIT.
# Source: sql/butter/ticket.sql

import typing

import aiosqlite
import pydantic

import app.types


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- create_table_ticket (:exec) ----

CREATE_TABLE_TICKET_1 = """
CREATE TABLE IF NOT EXISTS ticket (
    reference TEXT NOT NULL UNIQUE COLLATE NOCASE,
    label TEXT,
    reason TEXT,

    -- the last time the ticket was seen by the importer
    last_seen_at TEXT,

    -- when the ticket became active (if it is)
    active_since TEXT,

    -- see app.types.Status
    status TEXT NOT NULL
)
"""

CREATE_TABLE_TICKET_2 = """
CREATE INDEX IF NOT EXISTS idx_ticket_reason ON ticket (reason)
"""

CREATE_TABLE_TICKET_3 = """
CREATE INDEX IF NOT EXISTS idx_ticket_last_seen_at ON ticket (last_seen_at)
"""

CREATE_TABLE_TICKET_4 = """
CREATE INDEX IF NOT EXISTS idx_ticket_active_since ON ticket (active_since)
"""

CREATE_TABLE_TICKET_5 = """
CREATE INDEX IF NOT EXISTS idx_ticket_status ON ticket (status)
"""


async def create_table_ticket(
    cursor: aiosqlite.Cursor,
) -> None:
    """Runs `create_table_ticket`."""
    await cursor.execute(CREATE_TABLE_TICKET_1)
    await cursor.execute(CREATE_TABLE_TICKET_2)
    await cursor.execute(CREATE_TABLE_TICKET_3)
    await cursor.execute(CREATE_TABLE_TICKET_4)
    await cursor.execute(CREATE_TABLE_TICKET_5)


# ---- select_many_ticket (:many) ----


class SelectManyTicketRow(pydantic.BaseModel):
    """One result row of `select_many_ticket`."""

    reference: str
    label: str | None
    reason: str | None
    last_seen_at: app.types.SqlUtcTimestamp | None
    active_since: app.types.SqlUtcTimestamp | None
    status: app.types.Status


SELECT_MANY_TICKET = """
SELECT *
FROM ticket
"""


async def select_many_ticket(
    cursor: aiosqlite.Cursor,
) -> list[SelectManyTicketRow]:
    """Runs `select_many_ticket`."""
    await cursor.execute(SELECT_MANY_TICKET)
    return [SelectManyTicketRow.model_validate(_row_dict(SelectManyTicketRow, row)) for row in await cursor.fetchall()]


# ---- select_many_ticket_by_status (:many) ----


class SelectManyTicketByStatusRow(pydantic.BaseModel):
    """One result row of `select_many_ticket_by_status`."""

    reference: str
    label: str | None
    reason: str | None
    last_seen_at: app.types.SqlUtcTimestamp | None
    active_since: app.types.SqlUtcTimestamp | None
    status: app.types.Status


class SelectManyTicketByStatusParams(pydantic.BaseModel):
    """Parameters of `select_many_ticket_by_status`."""

    status: app.types.Status


SELECT_MANY_TICKET_BY_STATUS = """
SELECT *
FROM ticket
WHERE status = :status
"""


async def select_many_ticket_by_status(
    cursor: aiosqlite.Cursor,
    *,
    status: app.types.Status,
) -> list[SelectManyTicketByStatusRow]:
    """Runs `select_many_ticket_by_status`."""
    params = SelectManyTicketByStatusParams(status=status).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_TICKET_BY_STATUS, params)
    return [SelectManyTicketByStatusRow.model_validate(_row_dict(SelectManyTicketByStatusRow, row)) for row in await cursor.fetchall()]


# ---- select_many_ticket_filtered (:many) ----


class SelectManyTicketFilteredRow(pydantic.BaseModel):
    """One result row of `select_many_ticket_filtered`."""

    reference: str
    label: str | None
    reason: str | None
    last_seen_at: app.types.SqlUtcTimestamp | None
    active_since: app.types.SqlUtcTimestamp | None
    status: app.types.Status


class SelectManyTicketFilteredParams(pydantic.BaseModel):
    """Parameters of `select_many_ticket_filtered`."""

    status: app.types.Status | None = pydantic.Field(default=None)


SELECT_MANY_TICKET_FILTERED = """
SELECT *
FROM ticket
WHERE (:status IS NULL OR status = :status)
"""


async def select_many_ticket_filtered(
    cursor: aiosqlite.Cursor,
    *,
    status: app.types.Status | None = None,
) -> list[SelectManyTicketFilteredRow]:
    """Pass `status=None` to return every row."""
    params = SelectManyTicketFilteredParams(status=status).model_dump(by_alias=True)
    await cursor.execute(SELECT_MANY_TICKET_FILTERED, params)
    return [SelectManyTicketFilteredRow.model_validate(_row_dict(SelectManyTicketFilteredRow, row)) for row in await cursor.fetchall()]


# ---- insert_many_ticket (:execmany) ----


class InsertManyTicketParams(pydantic.BaseModel):
    """Parameters of `insert_many_ticket`."""

    reference: str
    label: str | None = pydantic.Field(default=None)
    reason: str | None = pydantic.Field(default=None)
    last_seen_at: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    active_since: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    status: app.types.Status


INSERT_MANY_TICKET = """
INSERT INTO ticket (reference, label, reason, last_seen_at, active_since, status)
VALUES (:reference, :label, :reason, :last_seen_at, :active_since, :status)
"""


async def insert_many_ticket(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyTicketParams],
) -> int:
    """Runs `insert_many_ticket`."""
    await cursor.executemany(INSERT_MANY_TICKET, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- insert_many_ticket_ignore_conflicts (:execmany) ----


class InsertManyTicketIgnoreConflictsParams(pydantic.BaseModel):
    """Parameters of `insert_many_ticket_ignore_conflicts`."""

    reference: str
    label: str | None = pydantic.Field(default=None)
    reason: str | None = pydantic.Field(default=None)
    last_seen_at: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    active_since: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    status: app.types.Status


INSERT_MANY_TICKET_IGNORE_CONFLICTS = """
INSERT INTO ticket (reference, label, reason, last_seen_at, active_since, status)
VALUES (:reference, :label, :reason, :last_seen_at, :active_since, :status)
ON CONFLICT(reference) DO NOTHING
"""


async def insert_many_ticket_ignore_conflicts(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[InsertManyTicketIgnoreConflictsParams],
) -> int:
    """Runs `insert_many_ticket_ignore_conflicts`."""
    await cursor.executemany(INSERT_MANY_TICKET_IGNORE_CONFLICTS, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- upsert_many_ticket (:execmany) ----


class UpsertManyTicketParams(pydantic.BaseModel):
    """Parameters of `upsert_many_ticket`."""

    reference: str
    label: str | None = pydantic.Field(default=None)
    reason: str | None = pydantic.Field(default=None)
    last_seen_at: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    active_since: app.types.SqlUtcTimestamp | None = pydantic.Field(default=None)
    status: app.types.Status


UPSERT_MANY_TICKET = """
INSERT INTO ticket (reference, label, reason, last_seen_at, active_since, status)
VALUES (:reference, :label, :reason, :last_seen_at, :active_since, :status)
ON CONFLICT(reference) DO UPDATE SET
    label = excluded.label,
    reason = excluded.reason,
    last_seen_at = excluded.last_seen_at
"""


async def upsert_many_ticket(
    cursor: aiosqlite.Cursor,
    rows: typing.Iterable[UpsertManyTicketParams],
) -> int:
    """Refreshes the label, reason and last-seen time of an existing ticket."""
    await cursor.executemany(UPSERT_MANY_TICKET, [row.model_dump(by_alias=True) for row in rows])
    return cursor.rowcount


# ---- archive_stale_ticket (:execrows) ----


class ArchiveStaleTicketParams(pydantic.BaseModel):
    """Parameters of `archive_stale_ticket`."""

    duration: str


ARCHIVE_STALE_TICKET = """
UPDATE ticket
SET status = 'ARCHIVED', active_since = NULL
WHERE last_seen_at < datetime('now', :duration)
"""


async def archive_stale_ticket(
    cursor: aiosqlite.Cursor,
    *,
    duration: str,
) -> int:
    """`duration` is a SQLite modifier such as '-7 days'."""
    params = ArchiveStaleTicketParams(duration=duration).model_dump(by_alias=True)
    await cursor.execute(ARCHIVE_STALE_TICKET, params)
    return cursor.rowcount


# ---- activate_recent_ticket (:execrows) ----


class ActivateRecentTicketParams(pydantic.BaseModel):
    """Parameters of `activate_recent_ticket`."""

    count: int


ACTIVATE_RECENT_TICKET = """
UPDATE ticket
SET status = iif(active_since IS NULL, 'PENDING', 'ACTIVE'),
    active_since = datetime('now')
WHERE rowid IN (
    SELECT rowid
    FROM ticket
    WHERE status != 'ARCHIVED'
    ORDER BY last_seen_at DESC
    LIMIT :count
)
"""


async def activate_recent_ticket(
    cursor: aiosqlite.Cursor,
    *,
    count: int,
) -> int:
    """
    Promotes the `count` most recently seen tickets: new ones become PENDING,
    already-started ones become ACTIVE.
    """
    params = ActivateRecentTicketParams(count=count).model_dump(by_alias=True)
    await cursor.execute(ACTIVATE_RECENT_TICKET, params)
    return cursor.rowcount


# ---- archive_inactive_ticket (:execrows) ----

ARCHIVE_INACTIVE_TICKET = """
UPDATE ticket
SET active_since = NULL, status = 'ARCHIVED'
WHERE status NOT IN ('ACTIVE', 'PENDING') AND active_since IS NOT NULL
"""


async def archive_inactive_ticket(
    cursor: aiosqlite.Cursor,
) -> int:
    """Runs `archive_inactive_ticket`."""
    await cursor.execute(ARCHIVE_INACTIVE_TICKET)
    return cursor.rowcount


# ---- update_status_ticket (:execrows) ----


class UpdateStatusTicketParams(pydantic.BaseModel):
    """Parameters of `update_status_ticket`."""

    set_status: app.types.Status


UPDATE_STATUS_TICKET = """
UPDATE ticket
SET status = :set_status
"""


async def update_status_ticket(
    cursor: aiosqlite.Cursor,
    *,
    set_status: app.types.Status,
) -> int:
    """Runs `update_status_ticket`."""
    params = UpdateStatusTicketParams(set_status=set_status).model_dump(by_alias=True)
    await cursor.execute(UPDATE_STATUS_TICKET, params)
    return cursor.rowcount


# ---- update_status_ticket_by_status (:execrows) ----


class UpdateStatusTicketByStatusParams(pydantic.BaseModel):
    """Parameters of `update_status_ticket_by_status`."""

    set_status: app.types.Status
    where_status: app.types.Status


UPDATE_STATUS_TICKET_BY_STATUS = """
UPDATE ticket
SET status = :set_status
WHERE status = :where_status
"""


async def update_status_ticket_by_status(
    cursor: aiosqlite.Cursor,
    *,
    set_status: app.types.Status,
    where_status: app.types.Status,
) -> int:
    """Runs `update_status_ticket_by_status`."""
    params = UpdateStatusTicketByStatusParams(set_status=set_status, where_status=where_status).model_dump(by_alias=True)
    await cursor.execute(UPDATE_STATUS_TICKET_BY_STATUS, params)
    return cursor.rowcount


# ---- delete_ticket_by_status (:execrows) ----


class DeleteTicketByStatusParams(pydantic.BaseModel):
    """Parameters of `delete_ticket_by_status`."""

    where_status: app.types.Status


DELETE_TICKET_BY_STATUS = """
DELETE FROM ticket
WHERE status = :where_status
"""


async def delete_ticket_by_status(
    cursor: aiosqlite.Cursor,
    *,
    where_status: app.types.Status,
) -> int:
    """Runs `delete_ticket_by_status`."""
    params = DeleteTicketByStatusParams(where_status=where_status).model_dump(by_alias=True)
    await cursor.execute(DELETE_TICKET_BY_STATUS, params)
    return cursor.rowcount


# ---- count_ticket_by_status (:many) ----


class CountTicketByStatusRow(pydantic.BaseModel):
    """One result row of `count_ticket_by_status`."""

    status: app.types.Status
    total: int
    latest_seen: app.types.SqlUtcTimestamp | None


COUNT_TICKET_BY_STATUS = """
SELECT status, COUNT(*) AS total, MAX(last_seen_at) AS latest_seen
FROM ticket
GROUP BY status
ORDER BY status
"""


async def count_ticket_by_status(
    cursor: aiosqlite.Cursor,
) -> list[CountTicketByStatusRow]:
    """Runs `count_ticket_by_status`."""
    await cursor.execute(COUNT_TICKET_BY_STATUS)
    return [CountTicketByStatusRow.model_validate(_row_dict(CountTicketByStatusRow, row)) for row in await cursor.fetchall()]
