# Code generated by butter. DO NOT EDIT.
# Source: queries/find_account.sql

import typing

import aiosqlite
import pydantic


def _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:
    """Maps a result row onto the model's fields by position, so unaliased expressions work."""
    return dict(zip(model.model_fields, row, strict=True))


# ---- find_account (:one) ----


class FindAccountRow(pydantic.BaseModel):
    """One result row of `find_account`."""

    id: int
    email: str
    profile: typing.Any | None
    status: str
    balance: float


class FindAccountParams(pydantic.BaseModel):
    """Parameters of `find_account`."""

    email: str
    limit: int


FIND_ACCOUNT = """
SELECT id, email, profile, status, balance
FROM accounts
WHERE email = ?
LIMIT ?
"""


async def find_account(
    cursor: aiosqlite.Cursor,
    *,
    email: str,
    limit: int,
) -> FindAccountRow | None:
    """Runs `find_account`."""
    params = tuple(FindAccountParams(email=email, limit=limit).model_dump(by_alias=True).values())
    await cursor.execute(FIND_ACCOUNT, params)
    row = await cursor.fetchone()
    return FindAccountRow.model_validate(_row_dict(FindAccountRow, row)) if row is not None else None
