# Code generated by butter. DO NOT EDIT.
# Source: queries/upsert_account.sql

import aiosqlite
import pydantic


# ---- upsert_account (:execrows) ----


class UpsertAccountParams(pydantic.BaseModel):
    """Parameters of `upsert_account`."""

    email: str
    status: str
    balance: float


UPSERT_ACCOUNT = """
INSERT INTO accounts (email, status, balance)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE balance = VALUES(balance)
"""


async def upsert_account(
    cursor: aiosqlite.Cursor,
    *,
    email: str,
    status: str,
    balance: float,
) -> int:
    """Runs `upsert_account`."""
    params = tuple(UpsertAccountParams(email=email, status=status, balance=balance).model_dump(by_alias=True).values())
    await cursor.execute(UPSERT_ACCOUNT, params)
    return cursor.rowcount
