//! Python code generation: one module per SQL file, targeting `aiosqlite`
//! cursors and `pydantic` models.

use std::collections::BTreeSet;

use crate::analyze::Param;
use crate::config::PythonConfig;
use crate::generate::{Module, QueryUnit};
use crate::queryfile::Command;
use crate::schema::Column;
use crate::types::{SqlType, TypeInfo};

const PYTHON_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "case", "class",
    "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if",
    "import", "in", "is", "lambda", "match", "nonlocal", "not", "or", "pass", "raise", "return",
    "try", "type", "while", "with", "yield",
];

/// Names the generated function bodies use for their own locals.
const RESERVED_PARAM_NAMES: &[&str] = &["cursor", "rows", "row", "params", "self", "cls"];

const STDLIB_MODULES: &[&str] = &[
    "abc", "collections", "dataclasses", "datetime", "decimal", "enum", "functools", "ipaddress",
    "json", "pathlib", "re", "typing", "uuid",
];

pub fn render_init() -> String {
    String::from("# Code generated by butter. Add re-exports here if you like; butter never overwrites this file.\n")
}

pub fn pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn is_python_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_alphanumeric() || c == '_')
}

/// Makes a SQL column or parameter name usable as a Python attribute.
fn python_field_name(name: &str, reserved: &[&str]) -> String {
    let mut out: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();

    if out.is_empty() {
        out = String::from("field");
    }
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        out = format!("_{}", out);
    }
    if PYTHON_KEYWORDS.contains(&out.as_str()) || reserved.contains(&out.as_str()) {
        out.push('_');
    }
    if !is_python_identifier(&out) {
        out = format!("field_{}", out);
    }
    out
}

fn escape_triple_quoted(sql: &str) -> String {
    sql.replace('\\', "\\\\").replace("\"\"\"", "\\\"\\\"\\\"")
}

struct TypeResolver<'c> {
    config: &'c PythonConfig,
    imports: BTreeSet<String>,
}

impl<'c> TypeResolver<'c> {
    fn new(config: &'c PythonConfig) -> TypeResolver<'c> {
        let mut imports = BTreeSet::new();
        imports.insert(String::from("aiosqlite"));
        TypeResolver { config, imports }
    }

    /// Records `import x.y` for every dotted name in a user-written type.
    fn collect_imports(&mut self, type_expr: &str) {
        let mut token = String::new();
        let flush = |token: &mut String, imports: &mut BTreeSet<String>| {
            if let Some((module, _)) = token.rsplit_once('.') {
                if !module.is_empty() && module.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '.') {
                    imports.insert(module.to_string());
                }
            }
            token.clear();
        };

        for ch in type_expr.chars() {
            if ch.is_alphanumeric() || ch == '_' || ch == '.' {
                token.push(ch);
            } else {
                flush(&mut token, &mut self.imports);
            }
        }
        flush(&mut token, &mut self.imports);
    }

    fn lookup_override(map: &std::collections::BTreeMap<String, String>, key: &str) -> Option<String> {
        map.iter()
            .find(|(k, _)| k.eq_ignore_ascii_case(key))
            .map(|(_, v)| v.clone())
    }

    fn resolve(
        &mut self,
        type_info: &TypeInfo,
        source: Option<&(String, String)>,
        explicit: Option<&str>,
    ) -> String {
        if let Some(explicit) = explicit {
            self.collect_imports(explicit);
            return explicit.to_string();
        }

        let mut base: Option<String> = None;

        if let Some((table, column)) = source {
            let key = format!("{}.{}", table, column);
            base = Self::lookup_override(&self.config.column_types, &key);
        }

        if base.is_none() {
            if let Some(declared) = &type_info.declared {
                let key = declared.split('(').next().unwrap_or("").trim().to_uppercase();
                base = Self::lookup_override(&self.config.sql_types, &key);
            }
        }

        let base = match base {
            Some(custom) => {
                self.collect_imports(&custom);
                custom
            }
            None => self.default_type(type_info.sql_type),
        };

        if type_info.sql_type == SqlType::Any && !source.is_some_and(|_| base != "typing.Any") {
            return base;
        }

        if type_info.nullable && !base.contains("None") {
            format!("{} | None", base)
        } else {
            base
        }
    }

    fn default_type(&mut self, sql_type: SqlType) -> String {
        match sql_type {
            SqlType::Int => String::from("int"),
            SqlType::Float | SqlType::Numeric => String::from("float"),
            SqlType::Text | SqlType::Json => String::from("str"),
            SqlType::Blob => String::from("bytes"),
            SqlType::Bool => String::from("bool"),
            SqlType::Date => {
                self.imports.insert(String::from("datetime"));
                String::from("datetime.date")
            }
            SqlType::Time => {
                self.imports.insert(String::from("datetime"));
                String::from("datetime.time")
            }
            SqlType::DateTime => {
                self.imports.insert(String::from("datetime"));
                String::from("datetime.datetime")
            }
            SqlType::Any => {
                self.imports.insert(String::from("typing"));
                String::from("typing.Any")
            }
        }
    }
}

struct FieldSpec {
    python_name: String,
    sql_name: String,
    type_expr: String,
    nullable: bool,
}

fn param_fields(unit: &QueryUnit, resolver: &mut TypeResolver) -> Vec<FieldSpec> {
    let mut used: Vec<String> = Vec::new();
    unit.params
        .iter()
        .map(|param: &Param| {
            let explicit = unit
                .param_overrides
                .iter()
                .find(|(n, _)| n == &param.name)
                .map(|(_, t)| t.as_str());
            let type_expr = resolver.resolve(&param.type_info, param.source.as_ref(), explicit);

            let mut python_name = python_field_name(&param.name, RESERVED_PARAM_NAMES);
            while used.contains(&python_name) {
                python_name.push('_');
            }
            used.push(python_name.clone());

            FieldSpec {
                python_name,
                sql_name: param.name.clone(),
                type_expr,
                nullable: param.type_info.nullable || explicit.is_some_and(|t| t.contains("None")),
            }
        })
        .collect()
}

fn column_fields(unit: &QueryUnit, resolver: &mut TypeResolver) -> Vec<FieldSpec> {
    let mut used: Vec<String> = Vec::new();
    unit.columns
        .iter()
        .map(|column: &Column| {
            let explicit = unit
                .column_overrides
                .iter()
                .find(|(n, _)| n.eq_ignore_ascii_case(&column.name))
                .map(|(_, t)| t.as_str());
            let type_expr = resolver.resolve(&column.type_info, column.source.as_ref(), explicit);

            let mut python_name = python_field_name(&column.name, &[]);
            while used.contains(&python_name) {
                python_name.push('_');
            }
            used.push(python_name.clone());

            FieldSpec {
                python_name,
                sql_name: column.name.clone(),
                type_expr,
                nullable: column.type_info.nullable,
            }
        })
        .collect()
}

fn render_model(out: &mut String, class_name: &str, fields: &[FieldSpec], doc: &str, is_params: bool) {
    out.push_str(&format!("class {}(pydantic.BaseModel):\n", class_name));
    out.push_str(&format!("    \"\"\"{}\"\"\"\n\n", doc));

    if fields.is_empty() {
        out.push_str("    pass\n\n\n");
        return;
    }

    for field in fields {
        let needs_alias = field.python_name != field.sql_name;
        let mut line = format!("    {}: {}", field.python_name, field.type_expr);

        if is_params {
            let mut field_args: Vec<String> = Vec::new();
            if field.nullable {
                field_args.push(String::from("default=None"));
            }
            if needs_alias {
                field_args.push(format!("serialization_alias={:?}", field.sql_name));
            }
            if !field_args.is_empty() {
                line.push_str(&format!(" = pydantic.Field({})", field_args.join(", ")));
            }
        }

        out.push_str(&line);
        out.push('\n');
    }
    out.push_str("\n\n");
}

fn sql_constant_name(unit: &QueryUnit, index: usize) -> String {
    let base = unit.name.to_uppercase();
    if unit.statements.len() == 1 {
        base
    } else {
        format!("{}_{}", base, index + 1)
    }
}

fn render_sql_constants(out: &mut String, unit: &QueryUnit) {
    for (index, statement) in unit.statements.iter().enumerate() {
        out.push_str(&format!(
            "{} = \"\"\"\n{}\n\"\"\"\n\n",
            sql_constant_name(unit, index),
            escape_triple_quoted(&statement.sql)
        ));
    }
    out.push('\n');
}

fn render_function(out: &mut String, unit: &QueryUnit, row_class: &str, params_class: &str, fields: &[FieldSpec]) {
    let return_type = match unit.command {
        Command::One => format!("{} | None", row_class),
        Command::Many => format!("list[{}]", row_class),
        Command::Exec => String::from("None"),
        Command::ExecRows | Command::ExecMany => String::from("int"),
        Command::ExecLastId => String::from("int | None"),
    };

    // Signature.
    out.push_str(&format!("async def {}(\n", unit.name));
    out.push_str("    cursor: aiosqlite.Cursor,\n");

    if unit.command == Command::ExecMany {
        out.push_str(&format!("    rows: typing.Iterable[{}],\n", params_class));
    } else if !fields.is_empty() {
        out.push_str("    *,\n");
        for field in fields {
            let default = if field.nullable { " = None" } else { "" };
            out.push_str(&format!("    {}: {}{},\n", field.python_name, field.type_expr, default));
        }
    }
    out.push_str(&format!(") -> {}:\n", return_type));

    // Docstring.
    let mut doc_lines: Vec<String> = unit.doc.clone();
    if doc_lines.is_empty() {
        doc_lines.push(format!("Runs `{}`.", unit.name));
    }
    if doc_lines.len() == 1 {
        out.push_str(&format!("    \"\"\"{}\"\"\"\n", doc_lines[0].replace("\"\"\"", "'''")));
    } else {
        out.push_str("    \"\"\"\n");
        for line in &doc_lines {
            out.push_str(&format!("    {}\n", line.replace("\"\"\"", "'''")));
        }
        out.push_str("    \"\"\"\n");
    }

    let dump = if unit.positional {
        "tuple(row.model_dump(by_alias=True).values())"
    } else {
        "row.model_dump(by_alias=True)"
    };

    // Body.
    if unit.command == Command::ExecMany {
        out.push_str(&format!(
            "    await cursor.executemany({}, [{} for row in rows])\n",
            sql_constant_name(unit, 0),
            dump
        ));
        out.push_str("    return cursor.rowcount\n");
        return;
    }

    let has_params = !fields.is_empty();
    if has_params {
        let kwargs: Vec<String> = fields
            .iter()
            .map(|f| format!("{}={}", f.python_name, f.python_name))
            .collect();
        let constructed = format!("{}({})", params_class, kwargs.join(", "));
        let dumped = if unit.positional {
            format!("tuple({}.model_dump(by_alias=True).values())", constructed)
        } else {
            format!("{}.model_dump(by_alias=True)", constructed)
        };
        out.push_str(&format!("    params = {}\n", dumped));
    }

    for (index, statement) in unit.statements.iter().enumerate() {
        if has_params && statement.has_params {
            out.push_str(&format!(
                "    await cursor.execute({}, params)\n",
                sql_constant_name(unit, index)
            ));
        } else {
            out.push_str(&format!("    await cursor.execute({})\n", sql_constant_name(unit, index)));
        }
    }

    match unit.command {
        Command::One => {
            out.push_str("    row = await cursor.fetchone()\n");
            out.push_str(&format!(
                "    return {}.model_validate(_row_dict({}, row)) if row is not None else None\n",
                row_class, row_class
            ));
        }
        Command::Many => {
            out.push_str(&format!(
                "    return [{}.model_validate(_row_dict({}, row)) for row in await cursor.fetchall()]\n",
                row_class, row_class
            ));
        }
        Command::Exec => {}
        Command::ExecRows => out.push_str("    return cursor.rowcount\n"),
        Command::ExecLastId => out.push_str("    return cursor.lastrowid\n"),
        Command::ExecMany => unreachable!(),
    }
}

pub fn render_module(module: &Module, config: &PythonConfig) -> Result<String, String> {
    let mut resolver = TypeResolver::new(config);
    let first_party_root: Option<String> = config
        .output_dir
        .components()
        .find_map(|c| match c {
            std::path::Component::Normal(part) => part.to_str().map(|s| s.to_string()),
            _ => None,
        });
    let mut body = String::new();
    let needs_row_helper = module.units.iter().any(|u| u.command.returns_rows());
    if needs_row_helper {
        resolver.imports.insert(String::from("typing"));
        resolver.imports.insert(String::from("pydantic"));
    }

    for unit in &module.units {
        if !is_python_identifier(&unit.name) || PYTHON_KEYWORDS.contains(&unit.name.as_str()) {
            return Err(format!("query name `{}` is not a valid Python identifier", unit.name));
        }

        let pascal = pascal_case(&unit.name);
        let row_class = format!("{}Row", pascal);
        let params_class = format!("{}Params", pascal);

        let param_specs = param_fields(unit, &mut resolver);
        let column_specs = column_fields(unit, &mut resolver);

        let starts_with_class = unit.command.returns_rows() || !param_specs.is_empty();
        body.push_str(&format!(
            "# ---- {} ({}) ----\n{}",
            unit.name,
            command_label(unit.command),
            if starts_with_class { "\n\n" } else { "\n" }
        ));

        if unit.command.returns_rows() || !param_specs.is_empty() {
            resolver.imports.insert(String::from("pydantic"));
        }
        if unit.command == Command::ExecMany {
            resolver.imports.insert(String::from("typing"));
        }

        if unit.command.returns_rows() {
            render_model(
                &mut body,
                &row_class,
                &column_specs,
                &format!("One result row of `{}`.", unit.name),
                false,
            );
        }

        if !param_specs.is_empty() {
            render_model(
                &mut body,
                &params_class,
                &param_specs,
                &format!("Parameters of `{}`.", unit.name),
                true,
            );
        }

        render_sql_constants(&mut body, unit);
        render_function(&mut body, unit, &row_class, &params_class, &param_specs);
        body.push_str("\n\n");
    }

    let mut out = String::new();
    out.push_str("# Code generated by butter. DO NOT EDIT.\n");
    out.push_str(&format!("# Source: {}\n\n", module.source.display()));

    let mut stdlib: Vec<&String> = Vec::new();
    let mut third_party: Vec<&String> = Vec::new();
    let mut first_party: Vec<&String> = Vec::new();
    for import in &resolver.imports {
        let root = import.split('.').next().unwrap_or("");
        if STDLIB_MODULES.contains(&root) {
            stdlib.push(import);
        } else if first_party_root.as_deref() == Some(root) {
            first_party.push(import);
        } else {
            third_party.push(import);
        }
    }
    for group in [&stdlib, &third_party, &first_party] {
        if group.is_empty() {
            continue;
        }
        for import in group.iter() {
            out.push_str(&format!("import {}\n", import));
        }
        out.push('\n');
    }

    if needs_row_helper {
        out.push_str("\ndef _row_dict(model: type[pydantic.BaseModel], row: typing.Sequence[object]) -> dict[str, object]:\n");
        out.push_str("    \"\"\"Maps a result row onto the model's fields by position, so unaliased expressions work.\"\"\"\n");
        out.push_str("    return dict(zip(model.model_fields, row, strict=True))\n\n\n");
    } else {
        out.push('\n');
    }

    out.push_str(body.trim_end());
    out.push('\n');

    Ok(out)
}

fn command_label(command: Command) -> &'static str {
    match command {
        Command::One => ":one",
        Command::Many => ":many",
        Command::Exec => ":exec",
        Command::ExecRows => ":execrows",
        Command::ExecLastId => ":execlastid",
        Command::ExecMany => ":execmany",
    }
}
